# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `pg_column_byte_packer` gem.
# Please instead update this file by running `bin/tapioca gem pg_column_byte_packer`.

class ActiveRecord::ConnectionAdapters::SchemaCreation
  include ::PgColumnBytePacker::SchemaCreation
end

# source://pg_column_byte_packer//lib/pg_column_byte_packer/version.rb#1
module PgColumnBytePacker
  class << self
    # source://pg_column_byte_packer//lib/pg_column_byte_packer.rb#9
    def ordering_key_for_column(connection:, name:, sql_type:, primary_key:, nullable:, has_default:, type_schema: T.unsafe(nil)); end

    # source://pg_column_byte_packer//lib/pg_column_byte_packer.rb#5
    def sql_type_alignment_cache; end
  end
end

# source://pg_column_byte_packer//lib/pg_column_byte_packer/pg_dump.rb#2
module PgColumnBytePacker::PgDump
  class << self
    # source://pg_column_byte_packer//lib/pg_column_byte_packer/pg_dump.rb#52
    def _sort_table_lines(connection:, qualified_table:, lines:); end

    # source://pg_column_byte_packer//lib/pg_column_byte_packer/pg_dump.rb#3
    def sort_columns_for_definition_file(path, connection:); end
  end
end

# source://pg_column_byte_packer//lib/pg_column_byte_packer/schema_statements.rb#6
module PgColumnBytePacker::SchemaCreation
  # source://pg_column_byte_packer//lib/pg_column_byte_packer/schema_statements.rb#7
  def visit_TableDefinition(o); end
end

# source://pg_column_byte_packer//lib/pg_column_byte_packer/version.rb#2
PgColumnBytePacker::VERSION = T.let(T.unsafe(nil), String)
