inherit_from: .rubocop_base.yml

require:
  - rubocop-rails
  - rubocop-sorbet

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*.rb'

Rails/I18nLocaleTexts:
  Enabled: false

Sorbet/RedundantExtendTSig:
  Enabled: true
