gem:
  # Add your `gem` command parameters here:
  #
  exclude:
  - debug
  - web-console
  - annotate
  - capistrano
  - capistrano-bundler
  - capistrano-chruby
  - capistrano-rails
  - rubocop
  - rubocop-rails
  - rubocop-sorbet
  - bcrypt_pbkdf
  - ed25519
  - tapioca
  - yard
  - yard-sorbet
  - unparser
  # doc: true
  # workers: 5
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  # workers: 5
