# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `HandleStripeEventJob`.
# Please instead update this file by running `bin/tapioca dsl HandleStripeEventJob`.

class HandleStripeEventJob
  class << self
    sig { params(stripe_event: ::Stripe::Event).returns(T.any(HandleStripeEventJob, FalseClass)) }
    def perform_later(stripe_event); end

    sig { params(stripe_event: ::Stripe::Event).void }
    def perform_now(stripe_event); end
  end
end
