# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::Internal::SubscriptionsController`.
# Please instead update this file by running `bin/tapioca dsl Api::Internal::SubscriptionsController`.

class Api::Internal::SubscriptionsController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
