# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Webhooks::StripeController`.
# Please instead update this file by running `bin/tapioca dsl Webhooks::StripeController`.

class Webhooks::StripeController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
