# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::V1::PostsController`.
# Please instead update this file by running `bin/tapioca dsl Api::V1::PostsController`.

class Api::V1::PostsController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
